// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALIeT2Rn0_VSJCrzkx5ndILN57XtfBoTw',
    appId: '1:600382106923:web:d72fe77579d8a7d77c696e',
    messagingSenderId: '600382106923',
    projectId: 'language-app-2c388',
    authDomain: 'language-app-2c388.firebaseapp.com',
    storageBucket: 'language-app-2c388.firebasestorage.app',
    measurementId: 'G-5YYYM0F7E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-qH1vTamHvAPTaqIGZWCRD1LBzG0QQAo',
    appId: '1:600382106923:android:4ea3b09b68de56cd7c696e',
    messagingSenderId: '600382106923',
    projectId: 'language-app-2c388',
    storageBucket: 'language-app-2c388.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1OfKX3TKw7KuuHQE6Q24Rqi4-vUVS_6c',
    appId: '1:600382106923:ios:bb6b32fbac4c17027c696e',
    messagingSenderId: '600382106923',
    projectId: 'language-app-2c388',
    storageBucket: 'language-app-2c388.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1OfKX3TKw7KuuHQE6Q24Rqi4-vUVS_6c',
    appId: '1:600382106923:ios:bb6b32fbac4c17027c696e',
    messagingSenderId: '600382106923',
    projectId: 'language-app-2c388',
    storageBucket: 'language-app-2c388.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALIeT2Rn0_VSJCrzkx5ndILN57XtfBoTw',
    appId: '1:600382106923:web:37828aeaed4d334c7c696e',
    messagingSenderId: '600382106923',
    projectId: 'language-app-2c388',
    authDomain: 'language-app-2c388.firebaseapp.com',
    storageBucket: 'language-app-2c388.firebasestorage.app',
    measurementId: 'G-D4LLZVM879',
  );
}
