# Note: Each level is padded by 2 spaces
name: Flutter CI/CD

on:
  push:
    branches: [ "master" ] # Trigger on push to the master branch
  pull_request:
    branches: [ "master" ] # Trigger on pull requests targeting master

jobs:
  flutter_job:
    runs-on: ubuntu-latest # Changed to Ubuntu for compatibility with web builds

    steps:
      # Step 1: Clone the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Step 4: Build Flutter Web
      - name: Build Flutter Web
        run: flutter build web

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: build/web  # Directory containing Flutter web build
            force_orphan: true  # Creates orphan branch for first-time deployment
            user_name: 'github-ci[bot]'  # Commit user name
            user_email: 'github-actions[bot]@users.noreply.github.com'  # Commit email
            commit_message: 'Publish to gh-pages'  # Custom commit message
