# Note: Each level is padded by 2 spaces
name: Flutter CI/CD

on:
  push:
    branches: [ "master" ] # Trigger on push to the main branch
  pull_request:
    branches: [ "master" ] # Trigger on pull requests targeting main

jobs:
  flutter_job:
    runs-on: windows-latest

    steps:
      # Step 1: Clone the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Step 4: Deploy to GitHub Pages (optional, e.g., for web builds)
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        run: flutter build web
